print("Test Case Ke 1 : ")
satu = input("Masukan Nilai Pertama : ")
dua = float(input("Masukan Nilai Kedua : "))
hasil = float(satu) + float(dua)
hasil1 = "{:.2f}".format(hasil)
print("Hasil dari penjumlahan nilai pertama", satu, "dan nilai kedua ", dua, "adalah ", hasil1)
print("\n")
print("Test Case Ke 2 : ")
satu = float(input("Masukan Nilai Pertama : "))
dua = float(input("Masukan Nilai Kedua : "))
hasil = float(satu) + float(dua)
hasil1 = "{:.2f}".format(hasil)
print("Hasil dari penjumlahan nilai pertama", satu, "dan nilai kedua ", dua, "adalah ", hasil1)