nama = input("Nama  : ")
nim = input("NIM  : ")
par = input("Kelas Paralel  : ")
ttl = input("Tempat/Tanggal Lahir  : ")
alamat = input("Alamat  : ")
hobi = input("Hobby  : ")
hp = input("No. HP  : ")

print("\n")
print("Nama  :", nama)
print("NIM  :", nim)
print("Kelas Paralel  :", par)
print("Tempat/Tanggal Lahir  :", ttl)
print("Alamat  :", alamat)
print("Hobby  :", hobi)
print("No. HP  :", hp)