a, b, i, j, x, y = map(float, input("").split())
operasi = (((((a - b) * i) / j) - x) + y)
hasil = "{:.3f}".format(operasi)
print(hasil)
a, b = map(float, input("").split())
i, j = map(float, input("").split())
x, y = map(float, input("").split())
operasi = float(((((a - b) * i) / j) - x) + y)
hasil = "{:.3f}".format(operasi)
print(hasil)